apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: oidc-client-id
      remoteRef:
        key: kv/apps/homebox
        property: oidc-client-id
    - secretKey: oidc-client-secret
      remoteRef:
        key: kv/apps/homebox
        property: oidc-client-secret
    - secretKey: auth-api-key-pepper
      remoteRef:
        key: kv/apps/homebox
        property: auth-api-key-pepper