apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared-storage
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.20.0.21
  share: /mnt/tank/containers
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer 
allowVolumeExpansion: true
mountOptions:
  - nfsvers=3