apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vw-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: oidc-client-id
      remoteRef:
        key: kv/apps/vaultwarden
        property: oidc-client-id
    - secretKey: oidc-client-secret
      remoteRef:
        key: kv/apps/vaultwarden
        property: oidc-client-secret
