apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scripts
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: webscraper
      remoteRef:
        key: kv/apps/scriptexporter
        property: webscraper
