---
# defaultPodOptions:
#   securityContext:
#     runAsUser: 568
#     runAsGroup: 568
#     fsGroup: 568
#     fsGroupChangePolicy: "OnRootMismatch"
#     supplementalGroups:
#       - 65539
# defaultPodOptions:
#   annotations:
#     k8s.v1.cni.cncf.io/networks: |
#       [{
#         "name": "iot-vlan",
#         "namespace": "kube-system",
#         "ips": ["10.10.0.17/24"]
#       }]
  #tolerations:
  # - key: "HAsrv"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  #nodeSelector:
  #  node: HAsrv
controllers:
    homeassistant:
      type: statefulset
      containers:
        main:
          image:
            repository: homeassistant/home-assistant
            tag: 2025.10.3
            pullPolicy: IfNotPresent
          env:
            - name: DNS_SERVER_DOMAIN
              value: hass.bukla.hu
service:
  # Configure a service for the main application
  app:
    controller: homeassistant
    type: ClusterIP
    ports:
      http:
        port: 8123
ingress:
  # Configure an Ingress for the main application
  app:
    className: "nginx-internal"
    hosts:
      - host: hass.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - hass.bukla.hu
        secretName: wildcard-bukla-tls

persistence:
  config:
    existingClaim: homeassistant-config
  #bluetooth:
  #  enabled: true
  #  type: hostPath
  #  hostPath: /run/dbus
