---
# defaultPodOptions:
#   securityContext:
#     runAsUser: 568
#     runAsGroup: 568
#     fsGroup: 568
#     fsGroupChangePolicy: "OnRootMismatch"
#     supplementalGroups:
#       - 65539
defaultPodOptions:
  # tolerations:
  #  - key: "HAsrv"
  #    operator: "Equal"
  #    value: "true"
  #    effect: "NoExecute"
  nodeSelector:
    node: HAsrv
controllers:
    homeassistant:
      type: statefulset
      containers:
        main:
          image:
            repository: homeassistant/home-assistant
            tag: 2025.2.4
            pullPolicy: IfNotPresent
          env:
            - name: DNS_SERVER_DOMAIN
              value: homeassistant.bukla.hu
service:
  # Configure a service for the main application
  app:
    controller: homeassistant
    type: ClusterIP
    ports:
      http:
        port: 8123
ingress:
  # Configure an Ingress for the main application
  app:
    className: "nginx-internal"
    hosts:
      - host: homeassistant.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - homeassistant.bukla.hu
        secretName: wildcard-bukla-tls

persistence:
  config:
    existingClaim: homeassistant-config
  bluetooth:
    enabled: true
    type: hostPath
    hostPath: /run/dbus
