apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef:
        key: kv/apps/rustfs
        property: accesskey
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef:
        key: kv/apps/rustfs
        property: secretkey