ingress:
  enabled: false
gatewayApi:
  enabled: false
  # gatewayClass: eg
  # existingGateway: 
  #   name: gateway-internal-eg
  #   namespace: gateway-envoy
  # hostname: rustfs.raymol.com

config:
  rustfs:
    log_level: "error"
    obs_log_directory: "" # disable log dir
mode:
  standalone:
    enabled: true
    existingClaim:
      dataClaim: rustfs-data
  distributed:
    enabled: false
secret:
  existingSecret: "rustfs-secret"
