apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: db_pw
      remoteRef:
        key: kv/database/postgres/paperless
        property: password
    - secretKey: db_user
      remoteRef:
        key: kv/database/postgres/paperless
        property: username
    - secretKey: redis-url
      remoteRef:
        key: kv/database/redis/
        property: url-cred-svc
    - secretKey: oidc-config
      remoteRef:
        key: kv/apps/paperless
        property: oidc-config
    - secretKey: rclone_config_file
      remoteRef:
        key: kv/apps/rclone
        property: rclone_config_file
