apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: db_pw
      remoteRef:
        key: kv/database/postgres/paperless
        property: password
    - secretKey: db_user
      remoteRef:
        key: kv/database/postgres/paperless
        property: username
