---
defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 568

controllers:
    main:
      containers:
        paperless:
          image:
            repository: ghcr.io/paperless-ngx/paperless-ngx
            tag: 2.20.14
            pullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: db_pw
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: db_user
            - name: PAPERLESS_REDIS
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: redis-url
            - name: PAPERLESS_CONSUMER_POLLING
              value: 60
            - name: PAPERLESS_LOGGING_DIR
              value: /tmp/paperless-logs
            - name: PAPERLESS_OCR_LANGUAGES
              value: eng deu
            - name: PAPERLESS_URL
              value: "https://paper.raymol.com"
            - name: POSTGRES_DB
              value: paperless
            - name: PAPERLESS_APPS
              value: allauth.socialaccount.providers.openid_connect
            - name: PAPERLESS_LOGOUT_REDIRECT_URL
              value: "https://auth.raymol.com/application/o/paperless/end-session/"
            - name: PAPERLESS_DISABLE_REGULAR_LOGIN
              value: true
            - name: PAPERLESS_SOCIAL_AUTO_SIGNUP
              value: true
            - name: PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS
              value: true
            - name: PAPERLESS_SOCIALACCOUNT_PROVIDERS
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: oidc-config
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 250M
service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8000


route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - "paper.raymol.com"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: http

persistence:
  data:
    existingClaim: paperless-data
    advancedMounts:
      main:
        paperless:
        - path: /usr/src/paperless/data
          subPath: data
        - path: /usr/src/paperless/media
          subPath: media
        - path: /usr/src/paperless/consume
          subPath: consume