apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valami-test
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-csi"
