#---
#apiVersion: longhorn.io/v1beta2
#kind: RecurringJob
#metadata:
#  name: daily-snapshot
#  namespace: storage-longhorn
#spec:
#  concurrency: 3
#  retain: 3
#  cron: 0 4 * * *
#  groups:
#  - backup
#  labels: {}
#  name: daily-snapshot
#  task: snapshot
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: storage-longhorn
spec:
  concurrency: 3
  retain: 14
  cron: 0 5 * * *
  groups:
  - backup
  labels: {}
  name: daily-backup
  task: backup

