ingress:
  ingressClassName: nginx-internal
  enabled: true
  host: longhorn.bukla.hu
  tls: true
  tlsSecret: wildcard-bukla-tls

preUpgradeChecker:
  # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
  jobEnabled: false

persistence:
  reclaimPolicy: Retain
  defaultClass: false
  defaultClassReplicaCount: 2

defaultBackupStore:
  backupTarget: nfs://10.20.0.21:/mnt/tank/vault/backups/longhorn

metrics:
  serviceMonitor:
    enabled: true