existingObjstoreSecret: thanos-objectstore-secret
bucketweb:
  enabled: true
  resourcesPreset: "small"
  httpRoute:
    enabled: true
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - thanos-bucket.raymol.com
storegateway:
  enabled: true
  resourcesPreset: "medium"
  persistence:
    enabled: true
    storageClass: "longhorn-cache"
    size: 10Gi

compactor:
  enabled: true
  resourcesPreset: "medium"
  retentionResolutionRaw: 30d
  retentionResolution5m: 60d
  retentionResolution1h: 90d
  httpRoute:
    enabled: true
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - thanos-compactor.raymol.com
  persistence:
    enabled: true
    size: 100Gi
    storageClass: "nfs-csi"

query:
  enabled: true
  replicaLabel:
    - replica
  resourcesPreset: "medium"
  dnsDsicovery:
    sidecarsNamespace: monitoring
    sidecarsService: prometheus-operated
  stores:
    - dnssrv+_grpc._tcp.prometheus-operated.monitoring.svc.cluster.local

queryFrontend:
  enabled: true
  resourcesPreset: "medium"
  httpRoute:
    enabled: true
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - thanos.raymol.com

image:
  registry: quay.io
  repository: thanos/thanos
  tag: v0.41.0

global:
  security:
    allowInsecureImages: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "monitoring"
  prometheusRule:
    enabled: true
    namespace: "monitoring"
