---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    # syncOptions:
    #   - ServerSideApply=true
    #   - Replace=true
  project: default
  sources:
    - repoURL: git@github.com:narwhal99/argocd.git
      targetRevision: HEAD
      path: applicationsets/monitoring