---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:narwhal99/argocd.git
    targetRevision: HEAD
    path: applicationsets/global
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}