---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:narwhal99/argocd.git
    targetRevision: HEAD
    path: global/
  destination:
    server: https://kubernetes.default.svc