---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:narwhal99/argocd.git
    targetRevision: HEAD
    path: global/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=true