apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-conf
  namespace: torrent
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
