apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: kv/database/postgres/authentik
        property: username
    - secretKey: password
      remoteRef:
        key: kv/database/postgres/authentik
        property: password