apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: kv/database/postgres/authentik
        property: url
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: kv/database/postgres/authentik
        property: username
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: kv/database/postgres/authentik
        property: password
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: kv/apps/authentik
        property: secret-key
    - secretKey: AUTHENTIK_EMAIL__HOST
      remoteRef:
        key: kv/apps/authentik
        property: no_reply_email_url
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: kv/apps/authentik
        property: no_reply_email_username
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: kv/apps/authentik
        property: no_reply_email_pw
    - secretKey: AUTHENTIK_EMAIL__FROM
      remoteRef:
        key: kv/apps/authentik
        property: no_reply_email_from

