global:
  envFrom:
    - secretRef:
        name: authentik-secrets
    - configMapRef:
        name: authentik-envs
server:
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    hosts:
      - auth.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - auth.bukla.hu
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: true

redis:
  enabled: true
  master:
    persistence:
      enabled: false