authentik:
  postgresql:
    host: psql.bukla.hu
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password

server:
  env:
    - name: AUTHENTIK_SECRET_KEY
      secretKeyRef:
        name: authentik-secret
        key: secret-key
  ingress:
    enabled: true
    hosts:
      - authentik-poc.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - authentik-poc.bukla.hu
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-secret
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
worker:
  env:
    - name: AUTHENTIK_SECRET_KEY
      secretKeyRef:
        name: authentik-secret
        key: secret-key
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-secret
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true