---
# defaultPodOptions:
#   securityContext:
#     runAsUser: 568
#     runAsGroup: 568
#     fsGroup: 568
#     fsGroupChangePolicy: "OnRootMismatch"
#     supplementalGroups:
#       - 65539

controllers:
    excalidraw:
      type: statefulset
      containers:
        main:
          image:
            repository: excalidraw/excalidraw
            tag: latest
            pullPolicy: IfNotPresent

service:
  # Configure a service for the main application
  app:
    controller: excalidraw
    type: ClusterIP
    ports:
      http:
        port: 80

ingress:
  # Configure an Ingress for the main application
  app:
    className: "nginx-internal"
    hosts:
      - host: draw.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - draw.bukla.hu
        secretName: wildcard-bukla-tls
# persistence:
#   config:
#     type: persistentVolumeClaim
#     storageClass: nfs-subdir
#     accessMode: ReadWriteOnce
#     size: 1Gi
#     globalMounts:
#       - path: /config

# configMaps:
#       config:
#         enabled: true
#         data:
#           config.yml: |
#             service:
#               enableregistration: false
#               timezone: Europe/Budapest
#               frontendUrl: https://vikunja.bukla.hu
#             auth:
#               local:
#                 enabled: false
#               openid:
#                 enabled: true
#                 redirecturl: https://vikunja.bukla.com/auth/openid/
#                 providers:
#                   - name: Authentik
#                     authurl: https://authentik.bukla.hu/application/o/authorize/
#                     logouturl: https://authentik.bukla.hu/application/o/vikunja/end-session/
#                     clientid: $authentik-client-id
#                     clientsecret: $authentik.client.secret
