---
controllers:
    main:
      type: statefulset
      containers:
        changedetection:
          image:
            repository: ghcr.io/dgtlmoon/changedetection.io
            tag: 0.47.03
            pullPolicy: IfNotPresent
          env:
            - name: WEBDRIVER_URL
              value: http://browser-chrome:4444/wd/hub
            - name: PLAYWRIGHT_DRIVER_URL
              value: ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
        playwright-chrome:
          image:
            repository: browserless/chrome
            tag: 1.60-chrome-stable
            pullPolicy: IfNotPresent
        browser-chrome:
          image:
            repository: selenium/standalone-chrome
            tag: 4
            pullPolicy: IfNotPresent
          env:
            - name: VNC_NO_PASSWORD
              value: 1

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 5000
ingress:
  main:
    className: "nginx"
    hosts:
      - host: scraper.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - scraper.bukla.hu
        secretName: wildcard-bukla-tls

# persistence:
#   config:
#     type: persistentVolumeClaim
#     storageClass: nfs-subdir
#     accessMode: ReadWriteOnce
#     size: 10Gi
#     globalMounts:
#       - path: /factorio