apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  namespace: argocd
spec:
  provider:
    vault:
      server: https://vault.bukla.hu/
      # namespace: "external-secrets"
      version: v2
      auth:
        appRole:
          path: "approle"
          roleId: "52570974-db2d-5c5d-23d2-b7c643ddf20b"
          secretRef:
            name: "vault-secret"
            namespace: "external-secrets"
            key: "secret-id"
