apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: sync-wildcard-cert-to-vault
  namespace: cert-manager
spec:
  updatePolicy: Replace
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: wildcard-bukla-tls
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: bukla.hu/wildcard-bukla-tls
          property: tls-cert
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: bukla.hu/wildcard-bukla-tls
          property: tls-key