apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plantit-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: database_host
      remoteRef:
        key: kv/database/mariadb/plantit
        property: url
    - secretKey: database_username
      remoteRef:
        key: kv/database/mariadb/plantit
        property: username
    - secretKey: database_password
      remoteRef:
        key: kv/database/mariadb/plantit
        property: password
    - secretKey: jwt_secret
      remoteRef:
        key: kv/apps/plantit
        property: jwt_secret
    - secretKey: FLORACODEX_KEY
      remoteRef:
        key: kv/apps/plantit
        property: FLORACODEX_KEY