---
controllers:
    plantit:
      containers:
        main:
          image:
            repository: msdeluise/plant-it-server
            tag: 0.10.0
            pullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: plantit-secrets
                  key: database_host
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: plantit-secrets
                  key: database_username
            - name: MYSQL_PSW
              valueFrom:
                secretKeyRef:
                  name: plantit-secrets
                  key: database_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: plantit-secrets
                  key: jwt_secret
            - name: FLORACODEX_KEY
              valueFrom:
                secretKeyRef:
                  name: plantit-secrets
                  key: FLORACODEX_KEY
            - name: MYSQL_DATABASE
              value: plantit
            - name: MYSQL_PORT
              value: 3306
            - name: JWT_EXP
              value: 1
            - name: USERS_LIMIT
              value: -1
            - name: UPLOAD_DIR
              value: "/upload-dir"
            - name: API_PORT
              value: 8080
            - name: LOG_LEVEL
              value: DEBUG
            - name: ALLOWED_ORIGINS
              value: "*"
            - name: CACHE_TYPE
              value: none
            # - name: CACHE_TTL
            #   value: 86400
            # - name: CACHE_HOST
            #   value: cache
            # - name: CACHE_PORT
            #   value: 6379
service:
  plantit:
    controller: plantit
    type: ClusterIP
    ports:
      http:
        port: 3000
      api:
        port: 8080
ingress:
  plantit:
    className: "nginx-internal"
    hosts:
      - host: plant.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: plantit
              port: http
          - path: /api
            pathType: Prefix
            service:
              identifier: plantit
              port: api
    tls:
      - hosts:
          - plant.bukla.hu
        secretName: wildcard-bukla-tls

persistence:
  uploaddir:
    existingClaim: plantit-upload-dir
    globalMounts:
      - path: /upload-dir