---
defaultPodOptions:
  securityContext:
    # runAsUser: 568
    # runAsGroup: 568
    # fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 65539

controllers:
  jackett:
    containers:
      app:
        image:
          repository: linuxserver/jackett
          tag: 0.22.583
          pullPolicy: IfNotPresent

service:
  app:
    controller: jackett
    ports:
      http:
        port: 9117

ingress:
  main:
    # className: "ingress-nginx"
    hosts:
      - host: jackett-k.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
persistence:
  config:
    type: persistentVolumeClaim
    storageClass: nfs-csi
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config
  # torrent:
  #   type: nfs
  #   server: 10.20.0.21
  #   path: /mnt/tank/torrent
  #   globalMounts:
  #     - path: /torrent