---
defaultPodOptions:
  automountServiceAccountToken: false
  securityContext:
    # runAsUser: 568
    # runAsGroup: 568
    # fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    # supplementalGroups:
    #   - 65539

controllers:
  jackett:
    type: statefulset
    containers:
      app:
        image:
          repository: linuxserver/jackett
          tag: 0.22.1468
          pullPolicy: IfNotPresent

service:
  app:
    controller: jackett
    ports:
      http:
        port: 9117

ingress:
  app:
    className: "nginx-internal"
    hosts:
      - host: jackett.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - jackett.bukla.hu
        secretName: wildcard-bukla-tls
persistence:
  config:
    type: persistentVolumeClaim
    storageClass: nfs-subdir
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config
  # torrent:
  #   type: nfs
  #   server: 10.20.0.21
  #   path: /mnt/tank/torrent
  #   globalMounts:
  #     - path: /torrent