apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 100Gi
