---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: kv/database/postgres/harbor
        property: password
