expose:
  tls:
    enabled: true
    secret:
      secretName: "wildcard-raymol-tls"
    certSource: secret
  type: route
  route:
    parentRefs:
    - kind: Gateway
      name: gateway-internal-eg
      namespace: gateway-envoy
    hosts:
    - "harbor.raymol.com"
externalURL: https://harbor.raymol.com

database:
  type: external
  external:
    host: "psql.raymol.com"
    port: "5432"
    username: "harbor"
    coreDatabase: "harbor"
    existingSecret: "harbor-secret"

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: "harbor"
      subPath: "registry"
    jobservice:
      jobLog:
        existingClaim: "harbor"
        subPath: "jobservice"
    redis:
      storageClass: "longhorn-cache"
      size: 500M

# redis: FIX: https://github.com/goharbor/harbor-helm/pull/2409
#   type: external
#   external:
#     addr: "redis.redis.svc.cluster.local:6379"
#     existingSecret: "harbor-secret"

trivy:
  enabled: false


core:
  extraEnvVars:
  - name: CONFIG_OVERWRITE_JSON
    valueFrom:
      secretKeyRef:
        name: harbor-secret
        key: OIDC_CONFIG