---
defaultPodOptions:
  securityContext:
    runAsUser: 911
    runAsGroup: 911
    fsGroup: 911
    fsGroupChangePolicy: "OnRootMismatch"
    # supplementalGroups:
    #   - 65539

controllers:
  main:
    type: deployment
    containers:
      prowlarr:
        image:
          repository: ghcr.io/home-operations/prowlarr
          tag: 2.3.6.5351
          pullPolicy: IfNotPresent
service:
  main:
    controller: main
    ports:
      http:
        port: 9696

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - "prowlarr.raymol.com"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: http

persistence:
  config:
    existingClaim: prowlarr-conf
    globalMounts:
      - path: /config
