apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: discord_webhook
      remoteRef:
        key: kv/apps/monitoring
        property: discord_webhook
