apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: clusteroutput-loki
spec:
  loki:
    url: http://loki-gateway.logging.svc
    configure_kubernetes_labels: true
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
      chunk_limit_size: 4MB
    # url: http://loki.logging.svc:3100/loki/api/v1/push
