apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: clusteroutput-loki
spec:
  loki:
    url: http://loki-gateway.logging.svc
    configure_kubernetes_labels: true
    buffer:
      timekey: 30s
      timekey_wait: 10s
      timekey_use_utc: true
      flush_interval: 1m
      chunk_limit_size: 8Mi