apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: clusteroutput-loki
spec:
  loki:
    url: http://loki-gateway.logging.svc
    # url: http://loki.logging.svc:3100/loki/api/v1/push