global:
  cattle:
    psp:
      enabled: false

additionalLoggingSources:
  rke:
    enabled: true

disablePvc: false
loggingOverlay:
  spec:
    fluentd:
      security:
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
        podSecurityPolicyCreate: false
        roleBasedAccessControlCreate: true
fluentd:
  metrics:
    serviceMonitor: true
    prometheusRules: true
  bufferStorageVolume:
    pvc:
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
fluentbit:
  metrics:
    serviceMonitor: true
    prometheusRules: true

monitoring:
  serviceMonitor:
    enabled: true