global:
  cattle:
    psp:
      enabled: false

additionalLoggingSources:
  rke:
    enabled: true

disablePvc: false
loggingOverlay:
  spec:
    errorOutputRef: "error-output-dlq"
    fluentd:
      scaling:
        replicas: 2
      security:
        podSecurityContext:
          runAsUser: 100
        podSecurityPolicyCreate: false
        roleBasedAccessControlCreate: true
fluentd:
  resources:
    limits:
      cpu: 1
      memory: 2Gi
  metrics:
    serviceMonitor: true
    prometheusRules: true
  bufferStorageVolume:
    pvc:
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
fluentbit:
  resources:
    limits:
      cpu: 500m
      memory: 250Mi
    requests:
      cpu: 200m
      memory: 50Mi
  metrics:
    serviceMonitor: true
    prometheusRules: true

monitoring:
  serviceMonitor:
    enabled: true
