apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tsig-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: rfc2136_tsig_secret
      remoteRef:
        key: kv/apps/externaldns
        property: tsig_key