provider: rfc2136
domainFilters:
  - bukla.hu
rfc2136:
  host: 10.20.0.4
  zone: bukla.hu
  tsigSecretAlg: hmac-sha512
  tsigKeyname: externaldns
  secretName: tsig-secret
  tsigAxfr: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

policy: sync
# tolerations:
#   - key: "HAsrv"
#     operator: "Equal"
#     value: "true"
#     effect: "NoExecute"
