domainFilters:
  - bukla.hu
provider: rfc2136

extraArgs:
  - --rfc2136-host=10.20.0.4
  - --rfc2136-port=53
  - --rfc2136-zone=bukla.hu
  - --rfc2136-min-ttl=0s
  - --rfc2136-tsig-axfr
  - --rfc2136-tsig-secret-alg=hmac-sha512
  - --rfc2136-tsig-keyname=externaldns

env:
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: tsig-secret
        key: rfc2136_tsig_secret

serviceMonitor:
  enabled: true

policy: sync