---
# defaultPodOptions:
#   securityContext:
#     runAsUser: 568
#     runAsGroup: 568
#     fsGroup: 568
#     fsGroupChangePolicy: "OnRootMismatch"
#     supplementalGroups:
#       - 65539
# defaultPodOptions:
  # tolerations:
  #  - key: "HAsrv"
  #    operator: "Equal"
  #    value: "true"
  #    effect: "NoExecute"
  # nodeSelector:
  #   node: HAsrv
controllers:
    technitiumdns:
      type: statefulset
      containers:
        main:
          image:
            repository: technitium/dns-server
            tag: 13.1
            pullPolicy: Always
          env:
            - name: DNS_SERVER_DOMAIN
              value: tech-dns02.bukla.hu
service:
  # Configure a service for the main application
  app:
    controller: technitiumdns
    type: LoadBalancer
    ports:
      tcp:
        port: 53
        protocol: TCP
      udp:
        port: 53
        protocol: UDP
      http:
        port: 5380
    annotations:
      metallb.universe.tf/allow-shared-ip: 10.20.0.115
      metallb.universe.tf/ip-allocated-from-pool: internal
      metallb.universe.tf/loadBalancerIPs: 10.20.0.115

ingress:
  # Configure an Ingress for the main application
  app:
    className: "nginx-internal"
    hosts:
      - host: tech-dns02.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - tech-dns02.bukla.hu
        secretName: wildcard-bukla-tls

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: nfs-subdir
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /etc/dns
