apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mktxp-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: _mktxp.conf
      remoteRef:
        key: kv/apps/mktxp
        property: _mktxp.conf
    - secretKey: mktxp.conf
      remoteRef:
        key: kv/apps/mktxp
        property: mktxp.conf