controllers:
    main:
      type: deployment
      containers:
        mktxp:
          image:
            repository: ghcr.io/akpw/mktxp
            tag: 1.2.17
            pullPolicy: IfNotPresent
          command: ["mktxp"]
          args:
            - --cfg-dir
            - /mktxp-config
            - export
service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 49090

serviceMonitor:
  main:
    enabled: true
    endpoints:
      - port: http
        scheme: http
        path: /metrics

persistence:
  config:
    type: secret
    name: mktxp-secret
    advancedMounts:
      main: 
        mktxp: 
          - path: /mktxp-config
            readOnly: false