apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: muse-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: vikunja-database-pw
      remoteRef:
        key: kv/apps/muse
        property: VIKUNJA_DATABASE_PASSWORD
    - secretKey: vikunja-service-jwtsecret
      remoteRef:
        key: kv/apps/muse
        property: VIKUNJA_SERVICE_JWTSECRET
    - secretKey: authentik-client-id
      remoteRef:
        key: kv/apps/muse
        property: AUTHENTIK_CLIENT_ID
    - secretKey: authentik_client_secret
      remoteRef:
        key: kv/apps/muse
        property: AUTHENTIK_CLIENT_SECRET