apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: muse-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: youtube_api_key
      remoteRef:
        key: kv/apps/muse
        property: youtube_api_key
    - secretKey: discord_token
      remoteRef:
        key: kv/apps/muse
        property: discord_token
    - secretKey: spotify_client_id
      remoteRef:
        key: kv/apps/muse
        property: spotify_client_id
    - secretKey: spotify_client_secret
      remoteRef:
        key: kv/apps/muse
        property: spotify_client_secret
