---
# defaultPodOptions:
#   securityContext:
#     runAsUser: 568
#     runAsGroup: 568
#     fsGroup: 568
#     fsGroupChangePolicy: "OnRootMismatch"
#     supplementalGroups:
#       - 65539

controllers:
  # Configure the main controller
  main:
    containers:
      main:
        image:
          repository: ghcr.io/museofficial/muse
          tag: 2.11.1
          pullPolicy: IfNotPresent
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: muse-secret
                key: discord_token
          - name: YOUTUBE_API_KEY
            valueFrom:
              secretKeyRef:
                name: muse-secret
                key: youtube_api_key
          - name: SPOTIFY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: muse-secret
                key: spotify_client_id
          - name: SPOTIFY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: muse-secret
                key: spotify_client_secret
persistence:
  data:
    existingClaim: muse-data
    globalMounts:
      - path: /data

# persistence:
#   data:
#     type: persistentVolumeClaim
#     storageClass: nfs-subdir
#     accessMode: ReadWriteOnce
#     size: 1Gi
#     globalMounts:
#       - path: /data