apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-storage-applicationset
  namespace: argocd
spec:
  template:
    metadata:
      name: global-storage
      namespace: argocd
    spec:
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: { }
        syncOptions:
          - CreateNamespace=true
      project: default
      sources:
        - repoURL: git@github.com:narwhal99/argocd.git
          targetRevision: HEAD
          path: global/
