apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: psql_username
      remoteRef:
        key: kv/database/postgres/bazarr
        property: username
    - secretKey: psql_pw
      remoteRef:
        key: kv/database/postgres/bazarr
        property: password
