apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-{{ .Values.spec.destination.cluster }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated: { }
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: x
      helm:
        valueFiles:
          - $values/values/{{ .Values.spec.source.cluster }}/monitoring/prometheus-stack.yaml
          - $values/values/{{ .Values.spec.source.cluster }}/monitoring/static_scraper_configs.yaml
        valuesObject:
          global:
            labels:
              stage: {{ .Values.spec.destination.namespace }}    
            env: {{ .Values.spec.destination.namespace }}
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
      # sources:
      #   - repoURL: https://bjw-s.github.io/helm-charts/
      #     chart: app-template
      #     targetRevision: x
      #     helm:
      #       valueFiles:
      #         - $values/values/{{ .namespace }}/mediabox/sonarr.yaml
      #         - $values/values/{{ .namespace }}/mediabox/qbittorrent.yaml
      #   - repoURL: git@github.com:narwhal99/argocd.git
      #     targetRevision: HEAD
      #     ref: values
