container_runtime: containerd

lapi:
  persistentVolume:
    # -- Persistent volume for data folder. Stores e.g. registered bouncer api keys
    data:
      enabled: false
      accessModes:
        - ReadWriteOnce
      storageClassName: ""
      existingClaim: ""
      size: 1Gi
    # -- Persistent volume for config folder. Stores e.g. online api credentials
    config:
      enabled: false
      accessModes:
        - ReadWriteOnce
      storageClassName: ""
      existingClaim: ""
      size: 100Mi
    # -- UI for crowdsec
  dashboard:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: "nginx-internal"
      host: "crowdsec.bukla.hu"
      tls: 
        - secretName: wildcard-bukla-tls

agent:
  acquisition:
    - namespace: "ingress-nginx"
      podName: "ingress-nginx-controller-*"
      program: "nginx"
      # -- If set to true, will poll the files using os.Stat instead of using inotify
      poll_without_inotify: false
  additionalAcquisition:
    - source: loki
      log_level: info
      url: http://loki.logging.svc.cluster.local:3100/
      # url: https://loki-gateway.bukla.hu
      limit: 1000
      query: |
        {container="haproxy"}
      labels:
        type: haproxy