apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: clusteroutput-loki
spec:
  loki:
    buffer:
      chunk_limit_size: 2M
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true
      flush_interval: 10s
      flush_mode: interval
      total_limit_size: 2Gi
      overflow_action: drop_oldest_chunk
    configure_kubernetes_labels: true
    url: http://loki-gateway.logging.svc
