apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: clusteroutput-loki
spec:
  loki:
    buffer:
      chunk_limit_size: 32M
      flush_interval: 15s
      flush_mode: interval
      overflow_action: drop_oldest_chunk
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    configure_kubernetes_labels: true
    url: http://loki-gateway.logging.svc
