replicaCount: 1

logging:
  enabled: true
  fluentd:
    metrics:
      serviceMonitor: true
    resources:
      limits:
        cpu: 1
        memory: 2Gi
    bufferStorageVolume:
      pvc:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
  fluentbit:
    metrics:
        serviceMonitor: true
    resources:
      limits:
        cpu: 500m
        memory: 250Mi
      requests:
        cpu: 200m
        memory: 50Mi
    inputTail:
      multiline.parser: ["docker", "cri"]
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        value: "true"
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        value: "true"

monitoring:
  serviceMonitor:
    enabled: true
