server:
  authModes:
    - sso
  httproute:
    enabled: true
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - "argowf.raymol.com"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
  sso:
    enabled: true
    issuer: https://auth.raymol.com/application/o/argowf/
    clientId:
      name: argowf-secrets
      key: client-id
    clientSecret:
      name: argowf-secrets
      key: client-secret
    redirectUrl: "https://argowf.raymol.com/oauth2/callback"
    rbac:
      enabled: false
singleNamespace: true
workflow:
  serviceAccount:
    create: true