# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: argocd-secret
# spec:
#   secretStoreRef:
#     name: vault
#     kind: ClusterSecretStore
#   data:
#     - secretKey: dex.authentik.clientSecret
#       remoteRef:
#         key: kv/apps/argocd
#         property: clientSecret
#     - secretKey: tls.crt
#       remoteRef:
#         key: kv/bukla.hu
#         property: cert.pem
#     - secretKey: tls.key
#       remoteRef:
#         key: kv/bukla.hu
#         property: cert-key.pem
#     - secretKey: admin.password
#       remoteRef:
#         key: kv/apps/argocd
#         property: adminpw

# EDIT argocd-secrets and add dex.authentik.clientSecret -> authentik