# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: argocd
# helmCharts:
# - name: argo-cd
#   repo: https://argoproj.github.io/argo-helm
#   version: 7.2.0
#   namespace: argocd
#   releaseName: argocd
#   valuesFile: values.yaml