---
# defaultPodOptions:
#   securityContext:
#     runAsUser: 568
#     runAsGroup: 568
#     fsGroup: 568
#     fsGroupChangePolicy: "OnRootMismatch"
#     supplementalGroups:
#       - 65539

controllers:
    snmp:
      type: statefulset
      containers:
        main:
          image:
            repository: prom/snmp-exporter
            tag: 0.26.0
            pullPolicy: IfNotPresent


service:
  # Configure an Ingress for the main application
  app:
    controller: snmp
    type: LoadBalancer
    ports:
      tcp:
        port: 9116
        protocol: TCP
    annotations:
      metallb.universe.tf/allow-shared-ip: 10.20.0.61
      metallb.universe.tf/ip-allocated-from-pool: default
      metallb.universe.tf/loadBalancerIPs: 10.20.0.61
# persistence:
#   # trainingData:
#   #   type: emptyDir
#   #   advancedMounts:
#   #     pdfstirling:
#   #       - path: /usr/share/tessdata
#   config:
#     type: persistentVolumeClaim
#     storageClass: nfs-subdir
#     accessMode: ReadWriteOnce
#     size: 1Gi
#     globalMounts:
#       - path: /configs

# configMaps:
#       config:
#         enabled: true
#         data:
#           config.yml: |
#             service:
#               enableregistration: false
#               timezone: Europe/Budapest
#               frontendUrl: https://vikunja.bukla.hu
#             auth:
#               local:
#                 enabled: false
#               openid:
#                 enabled: true
#                 redirecturl: https://vikunja.bukla.com/auth/openid/
#                 providers:
#                   - name: Authentik
#                     authurl: https://authentik.bukla.hu/application/o/authorize/
#                     logouturl: https://authentik.bukla.hu/application/o/vikunja/end-session/
#                     clientid: $authentik-client-id
#                     clientsecret: $authentik.client.secret
