ingress:
  enabled: true
  ingressClassName: nginx-internal
  hosts:
    - karma.raymol.com
  tls:
    - secretName: wildcard-bukla-tls
      hosts:
        - karma.raymol.com
httpRoute:
  enabled: true
  kind: HTTPRoute
  parentRefs:
    - kind: Gateway
      name: gateway-internal-eg
      namespace: gateway-envoy
  hostnames:
    - "karma.raymol.com"

configMap:
  enabled: true
  rawConfig:
    alertmanager:
      interval: 30s
      servers:
        - name: prometheus
          uri: http://alertmanager-operated:9093
          external_uri: "https://alertmanager.raymol.com"
          proxy: true
          healthcheck:
            filters:
              Watchdog:
                - alertname=Watchdog
                - severity=none
    filters:
      default:
        - "@state=active"
