---
# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  # Configure the main controller
  main:
    annotations:
      reloader.stakater.com/auto: "true"

    # # Configure the pod-specific securityContext
    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      # Configure the main application container
      main:
        image:
          # -- image repository
          repository: vikunja/vikunja
          # -- image tag
          # this example is not automatically updated, so be sure to use the latest image
          tag: latest
        # Configure the container-specific securityContext
        # securityContext:
        #   runAsUser: 568
        #   runAsGroup: 568
        env:
        - name: VIKUNJA_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: vikunja-database-pw
        - name: VIKUNJA_SERVICE_JWTSECRET
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: vikunja-service-jwtsecret
        - name: VIKUNJA_SERVICE_PUBLICURL
          value: https://vikunja.bukla.hu
        - name: VIKUNJA_DATABASE_HOST 
          value: mariadb.bukla.hu
        - name: VIKUNJA_DATABASE_TYPE 
          value: mysql
        - name: VIKUNJA_DATABASE_USER 
          value: vikunja
        - name: VIKUNJA_DATABASE_DATABASE 
          value: vikunja

service:
  # Configure a service for the main application
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 3456

ingress:
  # Configure an Ingress for the main application
  main:
    # className: "external-nginx"
    hosts:
      - host: vikunja.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    retain: true
    # existingClaim: vikunja-config
    storageClass: shared-storage
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /app/vikunja/files