apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: kv/database/postgres/firefly
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: kv/database/postgres/firefly
        property: password