---
loki:
  auth_enabled: false
  storage:
    type: filesystem
  commonConfig:
    replication_factor: 1
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  limits_config:
    retention_period: 60d
    max_label_names_per_series: 30
    # reject_old_samples: false
  # server:
  #   grpc_server_max_recv_msg_size: 15728640
  #   grpc_server_max_send_msg_size: 15728640
  schemaConfig:
    configs:
      - from: 2023-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester: # In Loki, the chunk_encoding field specifies the type of encoding to use for compressing log data chunks
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    max_concurrent: 8
  rulerConfig:
    storage:
      type: local
      local:
        directory: /var/loki/rules/
    rule_path: "/var/loki/rules-temp"
    ring:
      kvstore:
        store: inmemory
    alertmanager_url: http://alertmanager-operated.monitoring:9093
    enable_alertmanager_v2: true

gateway:
  nginxConfig:
    clientMaxBodySize: 50M
  ingress:
    ingressClassName: "nginx-internal"
    enabled: true
    hosts:
      - host: loki-gateway.bukla.hu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - loki-gateway.bukla.hu
        secretName: wildcard-bukla-tls

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
  extraEnv:
    # Keep a little bit lower than memory limits
    - name: GOMEMLIMIT
      value: 3750MiB
  persistence:
    storageClass: nfs-csi
    enabled: true
    size: 5Gi
  extraVolumeMounts:
    - name: rules
      mountPath: "/var/loki/rules/fake"
  extraVolumes:
    - name: rules
      configMap:
        name: loki-alerting-rules

networkPolicy:
  alertmanager:
    # -- Specify the alertmanager port used for alerting
    port: 9093
    # -- Specifies the alertmanager Pods.
    # As this is cross-namespace communication, you also need the namespaceSelector.
    podSelector:
    # -- Specifies the namespace the alertmanager is running in
    namespaceSelector: {}
# Zero out replica counts of other deployment modes

monitoring:
  dashboards:
    enabled: true
  rules:
    enabled: true
    labels:
      release: bukla
  serviceMonitor:
    enabled: true
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
