apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts/
    targetRevision: 3.5.1
    helm:
      valueFiles:
      - $repo/cluster/values/media/jellyseerr/values.yaml
      releaseName: jellyseerr
  - repoURL: git@github.com:narwhal99/argocd.git
    path: cluster/values/media/jellyseerr
    targetRevision: HEAD
    ref: repo
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
