apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: factorio-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: kv/apps/factorio
        property: token
