apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
