---
controllers:
    frigate:
      type: deployment
      containers:
        frigate:
          image:
            repository: ghcr.io/blakeblackshear/frigate
            tag: 0.17.1
            pullPolicy: IfNotPresent
service:
  frigate:
    controller: frigate
    type: ClusterIP
    ports:
      http:
        port: 5000

route:
  frigate:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - "cam.bukla.hu"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: frigate
            port: http

persistence:
  data:
    existingClaim: frigate
    advancedMounts:
      frigate:
        frigate:
        - path: /media/frigate
          subPath: records
        - path: /config
          subPath: config
  tmp:
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi
    advancedMounts:
      frigate:
        frigate:
        - path: /tmp/
  dshm:
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi
    advancedMounts:
      frigate:
        frigate:
        - path: /dev/shm