---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: api-token
      remoteRef:
        key: kv/apps/cert-manager
        property: cloudflare-api-token
