---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-helm-only
  namespace: argocd
spec:
  project: default
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.19.1
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      # alloweEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true