apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scrape-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: ns01_api_token
      remoteRef:
        key: kv/apps/prometheus/scrape
        property: ns01_api_token