apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: torrent-data
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.20.0.21
  share: /mnt/tank/containers/torrent
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer 
allowVolumeExpansion: true
mountOptions:
  - nfsvers=3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/tank/containers/torrent   # Replace with the path on your NFS server
    server: 10.20.0.21  # Replace with your NFS server address
  persistentVolumeReclaimPolicy: Retain
  storageClassName: torrent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: torrent-data