prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: cadvisor
      scrape_interval: 15s
      static_configs:
        - targets:
            - vmdocker04.bukla.hu:8080
            - raspi.bukla.hu:8080
            - vmeproxy.bukla.hu:8080
            - vmgames.bukla.hu:8080
            - lb.bukla.hu:8080
    - job_name: haproxy
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
        - targets:
          - lb.bukla.hu:5001
          - vmeproxy.bukla.hu:5001
    - job_name: node-exporter
      scrape_interval: 15s
      static_configs:
        - targets:
          - vmdocker04.bukla.hu:9100
          - raspi.bukla.hu:9100
          - pve01.bukla.hu:9100
          - vmeproxy.bukla.hu:9100
          - vmgames.bukla.hu:9100
          - lb.bukla.hu:9100
    - job_name: mikrotik
      scrape_interval: 5s
      static_configs:
        - targets:
            - 10.10.0.1 #mikrotik ip
      metrics_path: /snmp
      params:
        module: [mikrotik]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: raspi.bukla.hu:9116
  #  - job_name: blackbox_bukla
  #    metrics_path: /probe
  #    params:
  #      module: [http_2xx_bukla] 
  #    static_configs:
  #      - targets:
  #        - 
  #    relabel_configs:
  #      - source_labels: [__address__]
  #        target_label: __param_target
  #      - source_labels: [__param_target]
  #        target_label: instance
  #      - target_label: __address__
  #        replacement: vmdocker04.bukla.hu:9115  # The blackbox exporter's real hostname:port.
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [http_2xx] 
      static_configs:
        - targets:
          - https://jellyfin.bukla.hu
          - https://nextcloud.bukla.hu
          - https://tandoor.bukla.hu
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: vmdocker04.bukla.hu:9115  # The blackbox exporter's real hostname:port.
    - job_name: blackbox_icmp
      metrics_path: /probe
      params:
        module: [icmp_ipv4]
      static_configs:
        - targets:
          - c6140de057e0.sn.mynetname.net
          - pve01.mgmt.bukla.hu
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: vmdocker04.bukla.hu:9115  # The blackbox exporter's real hostname:port.
    - job_name: graphite-exporter 
      metrics_path: /metrics
      scrape_interval: 15s
      static_configs:
        - targets:
          - raspi.bukla.hu:9108
