grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - grafana-k.bukla.hu
  persistence:
    enabled: true
    type: sts
    storageClassName: shared-storage
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
  additionalDataSources:
    - name: influxdb
      uri: https://influxdb.bukla.hu
      type: influxdb
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        organization: "bukla"
      editable: true
  #     alertmanager:
  #       enabled: true
  #       name: Alertmanager
  #       uid: alertmanager
  #       handleGrafanaManagedAlerts: false
  #       implementation: prometheus
  env:
    - name: GF_AUTH_GENERIC_OAUTH_ENABLED
      value: true
    - name: GF_AUTH_GENERIC_OAUTH_NAME
      value: Authentik
    - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      value: hN3EgtiDqzqUwvvZJit5ExeYCVROMqjOyX4P0bNb
    - name: GF_AUTH_GENERIC_OAUTH_SCOPES
      value: "openid profile email"
    - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
      value: "https://authentik.bukla.hu/application/o/authorize/"
    - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
      value: "https://authentik.bukla.hu/application/o/token/"
    - name: GF_AUTH_GENERIC_OAUTH_API_URL
      value: "https://authentik.bukla.hu/application/o/userinfo/"
    - name: GF_AUTH_SIGNOUT_REDIRECT_URL
      value: "https://authentik.bukla.hu/application/o/grafana/end-session/"
    - name: GF_AUTH_OAUTH_AUTO_LOGIN
      value: "true"
    - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: monitoring-secret
          key: oidc_client_secret
thanos:
  enabled: false
prometheus:
  ingress:
    enabled: true
    hosts:
      - prom-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - prom-k.bukla.hu
  # prometheusOperator: #lehet nem kell
  #   admissionWebhooks:
  #     certManager:
  #       enabled: true
  prometheusSpec:
    ruleSelectorNiUsesHelmValues: false
    ruleSelector:
      matchLabels:
        rules: bukla
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-dev
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: shared-storage
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-dev
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: shared-storage
  ingress:
    enabled: true
    hosts:
      - alertmanager-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - alertmanager-k.bukla.hu
