grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - grafana-k.bukla.hu
  persistence:
    enabled: true
    type: sts
    storageClassName: nfs-csi
    accessModes:
      - ReadWriteOnce
    size: 20Gi
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
  additionalDataSources:
    - name: influxdb
      uri: https://influxdb.bukla.hu
      type: influxdb
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        organization: "bukla"
      editable: true
  #     alertmanager:
  #       enabled: true
  #       name: Alertmanager
  #       uid: alertmanager
  #       handleGrafanaManagedAlerts: false
  #       implementation: prometheus
  grafana.ini:
    "auth.anonymous":
      enabled: true
    check_for_updates: "false"
    server:
      root_url: "https://grafana.bukla.hu"
  envFromSecret: "grafana-secret"
  volumes:
    - name: grafana-secret
      secret:
        secretName: grafana-secret
        optional: false
  volumeMounts:
    - name: grafana-secret-vol
      mountPath: "/etc/grafana/grafana-secret"
      readOnly: true
thanos:
  enabled: false
prometheus:
  ingress:
    enabled: true
    hosts:
      - prom-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - prom-k.bukla.hu
  # prometheusOperator: #lehet nem kell
  #   admissionWebhooks:
  #     certManager:
  #       enabled: true
  prometheusSpec:
    replicas: 1
    ruleSelectorNiUsesHelmValues: false
    ruleSelector:
      matchLabels:
        rules: bukla
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data 
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: nfs-csi
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: nfs-csi
  ingress:
    enabled: true
    hosts:
      - alertmanager-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - alertmanager-k.bukla.hu
