grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - grafana-k.bukla.hu
  persistence:
    enabled: true
    type: sts
    storageClassName: nfs-csi
    accessModes:
      - ReadWriteOnce
    size: 20Gi
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
  additionalDataSources:
    - name: influxdb
      uri: https://influxdb.bukla.hu
      type: influxdb
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        organization: "bukla"
      editable: true
  #     alertmanager:
  #       enabled: true
  #       name: Alertmanager
  #       uid: alertmanager
  #       handleGrafanaManagedAlerts: false
  #       implementation: prometheus
  grafana.ini:
    check_for_updates: "false"
    server:
      root_url: "https://grafana.bukla.hu"
    # auth.generic_oauth:
    #   enabled: "true"
    #   name: Authentik
    #   client_id: hN3EgtiDqzqUwvvZJit5ExeYCVROMqjOyX4P0bNb
    #   client_secret:
    #   scopes: "openid profile email"
    #   auth_url: "https://authentik.bukla.hu/application/o/authorize/"
    #   token_url: "https://authentik.bukla.hu/application/o/token/"
    #   api_url: "https://authentik.bukla.hu/application/o/userinfo/"
    #   signout_redirect_url: "https://authentik.bukla.hu/application/o/grafana/end-session/"
    #   auto_login: "true"
  envFromSecret: "grafana-secret"
thanos:
  enabled: false
prometheus:
  ingress:
    enabled: true
    hosts:
      - prom-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - prom-k.bukla.hu
  # prometheusOperator: #lehet nem kell
  #   admissionWebhooks:
  #     certManager:
  #       enabled: true
  prometheusSpec:
    replicas: 1
    ruleSelectorNiUsesHelmValues: false
    ruleSelector:
      matchLabels:
        rules: bukla
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data 
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: nfs-csi
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: nfs-csi
  ingress:
    enabled: true
    hosts:
      - alertmanager-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - alertmanager-k.bukla.hu
