grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - grafana-k.bukla.hu
  persistence:
    enabled: true
    type: sts
    storageClassName: shared-storage
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
  additionalDataSources:
    - name: influxdb
      uri: https://influxdb.bukla.hu
      type: influxdb
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        organization: "bukla"
      editable: true
  #     alertmanager:
  #       enabled: true
  #       name: Alertmanager
  #       uid: alertmanager
  #       handleGrafanaManagedAlerts: false
  #       implementation: prometheus

thanos:
  enabled: false
prometheus:
  ingress:
    enabled: true
    hosts:
      - prom-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - prom-k.bukla.hu
  # prometheusOperator: #lehet nem kell
  #   admissionWebhooks:
  #     certManager:
  #       enabled: true
  prometheusSpec:
    ruleSelectorNiUsesHelmValues: false
    ruleSelector:
      matchLabels:
        rules: bukla
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-dev
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: shared-storage
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-dev
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: shared-storage
  ingress:
    enabled: true
    hosts:
      - alertmanager-k.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - alertmanager-k.bukla.hu
