apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-rules-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - list:
        elements:
          - namespace: dev
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'prometheus-rules-{{ .namespace }}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{ .namespace }}'
        server: '{{ .server }}'
      syncPolicy:
        automated: { }
        syncOptions:
          - CreateNamespace=true
      project: default
      sources:
        - repoURL: git@github.com:narwhal99/argocd.git
          targetRevision: HEAD
          path: monitoring/prometheus-rules
