apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - list:
        elements:
          - namespace: dev
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'prometheus-{{ .namespace }}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{ .namespace }}'
        server: '{{ .server }}'
      syncPolicy:
        automated: { }
        syncOptions:
          - CreateNamespace=true
      project: default
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: x
          helm:
            valueFiles:
              - $values/values/{{ .namespace }}/prometheus-stack.yaml
        - repoURL: git@github.com:narwhal99/argocd.git
          targetRevision: HEAD
          ref: values