---
controllers:
  main:
    type: deployment
    containers:
      zigbee2mqtt:
        image:
          repository: koenkk/zigbee2mqtt
          tag: 2.9.2
          pullPolicy: IfNotPresent
        env:
          - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
            value: "zigbee2mqtt"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
            value: "mqtt://mosquitto.apps.svc.cluster.local:1883"
          - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
            value: "tcp://10.90.0.10:6638"
          - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
            value: "ember"
          - name: ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED
            value: "true"
          - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED
            value: "true"
service:
  main:
    controller: main
    ports:
      http:
        port: 8080

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - "zigbee.raymol.com"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: http



persistence:
  data:
    existingClaim: zigbee2mqtt
    advancedMounts:
      main:
        zigbee2mqtt:
        - path: /app/data/
          subPath: data
