---
ingress:
  className: nginx
  enabled: true
  hosts:
    - snmp-exporter.bukla.hu
  tls:
    - secretName: wildcard-bukla-tls
      hosts:
        - snmp-exporter.bukla.hu
module:
  - mikrotik