apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-secrets
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: ocikms_seal_key_id
      remoteRef:
        key: kv/apps/vault
        property: ocikms_seal_key_id
    - secretKey: ocikms_crypto_endpoint
      remoteRef:
        key: kv/apps/vault
        property: ocikms_crypto_endpoint
    - secretKey: ocikms_management_endpoint
      remoteRef:
        key: kv/apps/vault
        property: ocikms_management_endpoint
    - secretKey: priv-key.pem
      remoteRef:
        key: kv/apps/vault
        property: oci_user_priv-key.pem
    - secretKey: config
      remoteRef:
        key: kv/apps/vault
        property: oci_user_config
