apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: svcaccts
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: loki-secretkey 
      remoteRef:
        key: kv/database/minio/loki
        property: access_secret
    - secretKey: thanos-secretkey 
      remoteRef:
        key: kv/database/minio/thanos
        property: access_secret
