apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: redis-password
      remoteRef:
        key: kv/database/redis
        property: password
