controller:
  kind: DaemonSet
  extraArgs:
    # default-ssl-certificate: ""
    enable-ssl-passthrough: "true"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      scrapeInterval: 15s
  service:
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/allow-shared-ip: 10.20.0.110
      metallb.universe.tf/ip-allocated-from-pool: internal
      metallb.universe.tf/loadBalancerIPs: 10.20.0.110
  config:
    enable-real-ip: "true"
    enable-underscores-in-headers: "true"
    server-tokens: "false"
    allow-snippet-annotations: "true"
    use-forwarded-headers: "true"
    # forwarded-for-header: "X-Forwarded-For"
    forwarded-for-header: "proxy_protocol"
  ingressClassResource:
    name: nginx-internal
    controllerValue: k8s.io/ingress-nginx-internal
  ingressClass: internal-nginx
  # tolerations:
  #  - key: "HAsrv"
  #    operator: "Equal"
  #    value: "true"
  #    effect: "NoExecute"
podSecurityPolicy:
  enabled: false