nameOverride: prometheus-helm
# alertmanager:
#   enabled: false
prometheus:
  enabled: true
  name: configmap-reload
  image:
    repository: quay.io/prometheus-operator/prometheus-config-reloader
    tag: v0.72.0
    digest: ""
    pullPolicy: IfNotPresent
server:
  name: server
  image:
    repository: quay.io/prometheus/prometheus
    tag: ""
    digest: ""
    pullPolicy: IfNotPresent