apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: database_password
      remoteRef:
        key: kv/database/mariadb/vikunja
        property: password
    - secretKey: database_username
      remoteRef:
        key: kv/database/mariadb/vikunja
        property: username
    - secretKey: database_host
      remoteRef:
        key: kv/database/mariadb/vikunja
        property: url
    - secretKey: vikunja-service-jwtsecret
      remoteRef:
        key: kv/apps/vikunja
        property: VIKUNJA_SERVICE_JWTSECRET
    - secretKey: authentik-client-id
      remoteRef:
        key: kv/apps/vikunja
        property: AUTHENTIK_CLIENT_ID
    - secretKey: authentik_client_secret
      remoteRef:
        key: kv/apps/vikunja
        property: AUTHENTIK_CLIENT_SECRET