kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vikunja-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: vikunja-config
  storageClassName: nfs-csi