---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-config
  finalizers:
  - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vikunja-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: vikunja-config
  storageClassName: nfs-csi