apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  config.yml: |
    service:
      enableregistration: false
      timezone: Europe/Budapest
      frontendUrl: https://vikunja.bukla.hu
    auth:
      local:
        enabled: false
      openid:
        enabled: true
        redirecturl: https://vikunja.bukla.com/auth/openid/
        providers:
          - name: Authentik
            authurl: https://authentik.bukla.hu/application/o/authorize/
            logouturl: https://authentik.bukla.hu/application/o/vikunja/end-session/
            clientid: "$authentik-client-id"
            clientsecret: "$authentik-client-secret"
