---
defaultPodOptions:
  securityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 65539

controllers:
    vikunja:
      type: statefulset
      containers:
        main:
          image:
            repository: vikunja/vikunja
            tag: latest
            pullPolicy: IfNotPresent
          env:
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: vikunja-database-pw
            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: vikunja-service-jwtsecret
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: https://vikunja.bukla.hu
            - name: VIKUNJA_DATABASE_HOST 
              value: mariadb.bukla.hu
            - name: VIKUNJA_DATABASE_TYPE 
              value: mysql
            - name: VIKUNJA_DATABASE_USER 
              value: vikunja
            - name: VIKUNJA_DATABASE_DATABASE 
              value: vikunja

service:
  # Configure a service for the main application
  app:
    controller: vikunja
    type: ClusterIP
    ports:
      http:
        port: 3456

ingress:
  # Configure an Ingress for the main application
  app:
    className: "nginx"
    hosts:
      - host: vikunja.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
persistence:
  config:
    type: persistentVolumeClaim
    storageClass: nfs-subdir
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config

# configMaps:
#       config:
#         enabled: true
#         data:
#           config.yml: |
#             service:
#               enableregistration: false
#               timezone: Europe/Budapest
#               frontendUrl: https://vikunja.bukla.hu
#             auth:
#               local:
#                 enabled: false
#               openid:
#                 enabled: true
#                 redirecturl: https://vikunja.bukla.com/auth/openid/
#                 providers:
#                   - name: Authentik
#                     authurl: https://authentik.bukla.hu/application/o/authorize/
#                     logouturl: https://authentik.bukla.hu/application/o/vikunja/end-session/
#                     clientid: $authentik-client-id
#                     clientsecret: $authentik.client.secret
