---
defaultPodOptions:
  securityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 65539

controllers:
  alternatrr:
    type: statefulset
    # type: statefulset
    # replicas: 3
    # statefulset:
    #   volumeClaimTemplates:
    #   - name: "storage"
    #     globalMounts:
    #       - path: /config
    #     accessMode: "ReadWriteOnce"
    #     size: "1Gi"
    #     storageClass: "nfs-csi"
    containers:
      app:
        image:
          repository: ghcr.io/theultimatec0der/alternatrr
          tag: latest
          pullPolicy: IfNotPresent
service:
  app:
    controller: alternatrr
    ports:
      http:
        port: 80

ingress:
  app:
    className: "nginx"
    hosts:
      - host: alternatrr.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - alternatrr.bukla.hu
        secretName: wildcard-bukla-tls
persistence:
  # config:
  #   enabled: true
  #   type: persistentVolumeClaim
    # existingClaim: alternatrr-test
  sonarr:
    existingClaim: sonarr-config
    advancedMounts:
      alternatrr:
        app:
          - path: /opt/sonarr
  config:
    type: persistentVolumeClaim
    storageClass: nfs-subdir
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /opt/alternatrr/app