---
defaultPodOptions:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node
            operator: NotIn
            values:
            - HAsrv
controllers:
    minecraft:
      containers:
        main:
          image:
            repository: itzg/minecraft-server
            tag: 2025.10.1
            pullPolicy: IfNotPresent
          tty: true
          stdin: true
          env:
            - name: VERSION
              value: "1.21.4"
            - name: EULA
              value: true
            - name: INIT_MEMORY
              value: 128m
            - name: MAX_MEMORY
              value: 10240m
            - name: VIEW_DISTANCE
              value: 15
            - name: TZ
              value: Europe/Budapest
            - name: MODE
              value: survival
            - name: DIFFICULTY
              value: hard
            - name: TYPE
              value: "FOLIA"
            - name: PLUGINS
              value: |
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.2/minecraft-prometheus-exporter-3.1.2.jar
          resources:
            limits:
              cpu: 4
              memory: 12Gi
            requests:
              cpu: 1
              memory: 4Gi
service:
  # Configure a service for the main application
  prometheus:
    controller: minecraft
    type: ClusterIP
    ports:
      http:
        port: 9940  
  app:
    controller: minecraft
    type: LoadBalancer
    ports:
      tcp:
        port: 25565
      udp:
        port: 25565
        protocol: UDP
    annotations:
      metallb.universe.tf/allow-shared-ip: 10.20.0.151
      metallb.universe.tf/ip-allocated-from-pool: external
      metallb.universe.tf/loadBalancerIPs: 10.20.0.151

serviceMonitor:
  main:
    enabled: true
    serviceName: minecraft-prometheus
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 30s
        scrapeTimeout: 10s
persistence:
  data:
    existingClaim: minecraft-data
    globalMounts:
      - path: /data

# configMaps:
#       config:
#         enabled: true
#         data:
#           config.yml: |
#             service:
#               enableregistration: false
#               timezone: Europe/Budapest
#               frontendUrl: https://vikunja.bukla.hu
#             auth:
#               local:
#                 enabled: false
#               openid:
#                 enabled: true
#                 redirecturl: https://vikunja.bukla.com/auth/openid/
#                 providers:
#                   - name: Authentik
#                     authurl: https://authentik.bukla.hu/application/o/authorize/
#                     logouturl: https://authentik.bukla.hu/application/o/vikunja/end-session/
#                     clientid: $authentik-client-id
#                     clientsecret: $authentik.client.secret
