grafana:
  enabled: false
thanos:
  enabled: false
prometheus:
  ingress:
    enabled: true
    hosts:
      - prom-rke.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - prom-rke.bukla.hu
  # prometheusOperator: #lehet nem kell
  #   admissionWebhooks:
  #     certManager:
  #       enabled: true
  prometheusSpec:
    ruleSelectorNiUsesHelmValues: false
    ruleSelector:
      matchLabels:
        rules: bukla
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-dev
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: shared-storage
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-dev
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: shared-storage
  ingress:
    enabled: true
    hosts:
      - alertmanager-rke.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - alertmanager-rke.bukla.hu
