grafana:
  enabled: false
thanos:
  enabled: false
prometheus:
  ingress:
    enabled: true
    hosts:
      - prom-rke.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - prom-rke.bukla.hu
  prometheusOperator: #lehet nem kell
    admissionWebhooks:
      certManager:
        enabled: true
  prometheusSpec:
    ruleSelectorNiUsesHelmValues: false
    ruleSelector:
      matchLabels:
        rules: bukla
    # storageSpec:
    #   VolumeClaimTemplate:
    #     metadata:
    #       name: prometheus-dev
    #     spec:
    #       accessModes:
    #         - ReadWriteOnce
    #       resources:
    #         request:
    #           storage: 1Gi
    #       storageClassName: random-name
alertmanager:
  # alertmanagerSpec:
  #   storage:
  #     VolumeClaimTemplate:
  #       metadata:
  #         name: alertmanager-dev
  #       spec:
  #         accessModes:
  #           - ReadWriteOnce
  #         resources:
  #           request:
  #             storage: 1Gi
  #         storageClassName: random-name
  ingress:
    enabled: true
    hosts:
      - alertmanager-rke.bukla.hu
    tls:
      - secretName: wildcard-bukla-tls
        hosts:
          - alertmanager-rke.bukla.hu
