apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: oidc_client_id
      remoteRef:
        key: kv/apps/trek
        property: oidc_client_id
    - secretKey: oidc_client_secret
      remoteRef:
        key: kv/apps/trek
        property: oidc_client_secret
    - secretKey: admin_email
      remoteRef:
        key: kv/apps/trek
        property: admin_email
    - secretKey: admin_password
      remoteRef:
        key: kv/apps/trek
        property: admin_pw
