apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
  labels:
    loki_rule: ""
data:
  rules.yaml: |
    groups:
      - name: Jellyfin_auth
        rules:
          - alert: Jellyfin_auth
            expr: |
              count_over_time({app_kubernetes_io_name="jellyfin"} |~ "Authentication" |= "denied"[5m]) > 0
            labels:
              severity: "critical"
            annotations:
              title: 'Wrong auth within 5 min'
      - name: SSH_Login_failed_by_pw
        rules:
          - alert: SSH_login_failed_pw
            expr: |
              sum by (user,ip) (count_over_time({job="hostlogs"} |= "Failed password" | pattern "<_> user <user> from <ip> <_>"[15m])) > 3
            labels:
              severity: "critical"
            annotations:
              title: 'SSH Login failed - User: {{ $labels.user }}, IP: {{ $labels.ip }}'
      - name: SSH_Login_failed_by_key
        rules:
          - alert: SSH_login_failed_key
            expr: |
              sum by (user,ip) (count_over_time({job="hostlogs"} |~ "sshd" |~ "Connection closed" | pattern "<_> user <user> <ip> <_>"[15m])) > 3
            labels:
              severity: "critical"
            annotations:
              title: 'SSH Login failed - User: {{ $labels.user }}, IP: {{ $labels.ip }}'
      - name: Mikrotik_login_failed
        rules:
          - alert: Mikrotik_login_failed
            expr: |
              count_over_time({host="10.12.0.1"} |= "failure"[2m]) > 0
            labels:
              severity: "critical"
            annotations:
              title: 'Mikrotik Login failed'
