---
defaultPodOptions:
  securityContext:
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"

controllers:
    main:
      pod:
        dnsPolicy: "None"
        dnsConfig:
          nameservers:
            - 127.0.0.1
          searches: []
          options:
            - name: ndots
              value: "1"
      containers:
        ytdl:
          image:
            repository: ghcr.io/alexta69/metube
            tag: 2026.04.28
            pullPolicy: IfNotPresent
          env:
            - name: MAX_CONCURRENT_DOWNLOADS
              value: 2
            - name: DOWNLOAD_DIR
              value: "/torrent"
            - name: DOWNLOAD_DIRS_INDEXABLE
              value: true
            - name: STATE_DIR
              value: "/torrent/downloads/metube/"
        gluetun:
          dependsOn: ytdl
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.41.1
          env:
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8"
            - name: FIREWALL_INPUT_PORTS
              value: 8081
            - name: BLOCK_MALICIOUS
              value: off
            - name: BLOCK_SURVEILLANCE
              value: off
            - name: BLOCK_ADS
              value: off
            - name: VPN_TYPE
              value: wireguard
            - name: VPN_INTERFACE
              value: wg0
            - name: WIREGUARD_ENDPOINT_PORT
              value: 51590
            - name: VPN_SERVICE_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: ytdl-secret
                  key: vpn_provider
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ytdl-secret
                  key: wg_priv_key
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: ytdl-secret
                  key: wg_addresses
            - name: SERVER_CITIES
              valueFrom:
                secretKeyRef:
                  name: ytdl-secret
                  key: vpn_provider_cities
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8081

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - "ytdl.raymol.com"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: http

persistence:
  downloads:
    type: nfs
    server: 10.20.0.21
    path: /mnt/tank/torrent
    globalMounts:
      - path: /torrent
