apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iot-vlan
  namespace: kube-system
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "ens19",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "subnet": "10.10.0.0/24",
        "rangeStart": "10.10.0.10",
        "rangeEnd": "10.10.0.20",
        "routes": [
          { "dst": "10.10.0.0/24", "gw": "10.10.0.1" }
        ],
        "gateway": "10.10.0.1"
      }
    }
