---
# defaultPodOptions:
#   securityContext:
#     runAsUser: 568
#     runAsGroup: 568
#     fsGroup: 568
#     fsGroupChangePolicy: "OnRootMismatch"
#     supplementalGroups:
#       - 65539

controllers:
  main:
    type: deployment
    containers:
      sabnzbd:
        image:
          repository: lscr.io/linuxserver/sabnzbd
          tag: 4.5.5
          pullPolicy: IfNotPresent
service:
  main:
    controller: main
    ports:
      http:
        port: 8080

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - kind: Gateway
        name: gateway-internal-eg
        namespace: gateway-envoy
    hostnames:
      - "sabnzbd.raymol.com"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: http

persistence:
  config:
    existingClaim: sabnzbd-conf
    globalMounts:
      - path: /config
  torrent:
    type: nfs
    server: 10.20.0.21
    path: /mnt/tank/torrent
    globalMounts:
      - path: /torrent