---
# defaultPodOptions:
#   securityContext:
#     runAsUser: 568
#     runAsGroup: 568
#     fsGroup: 568
#     fsGroupChangePolicy: "OnRootMismatch"
#     supplementalGroups:
#       - 65539

controllers:
  sabnzbd:
    type: statefulset
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/sabnzbd
          tag: 4.5.3
          pullPolicy: IfNotPresent
service:
  app:
    controller: sabnzbd
    ports:
      http:
        port: 8080

ingress:
  app:
    className: "nginx-internal"
    hosts:
      - host: sabnzbd.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - sabnzbd.bukla.hu
        secretName: wildcard-bukla-tls
persistence:
  config:
    existingClaim: sabnzbd-conf
    globalMounts:
      - path: /config
  torrent:
    type: nfs
    server: 10.20.0.21
    path: /mnt/tank/torrent
    globalMounts:
      - path: /torrent