apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: git@github.com:narwhal99/argocd.git
    targetRevision: HEAD
    path: applicationsets/prometheus
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      alloweEmpty: false
    syncOptions:
      - CreateNamespace=true