apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "2844097"
  installID: "109481996"
  # repositories: # optional
  #   - my-gitops-repo
  # permissions: # optional
  #   contents: read
  auth:
    privateKey:
      secretRef:
        name: renovate-bot-secrets
        key: private_key_pem
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-auth-token
spec:
  refreshInterval: "30m0s"
  target:
    name: github-auth-token
    template:
      type: Opaque
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: GithubAccessToken
        name: github-auth-token