apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-env-secrets
  namespace: renovatebot
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: kv/apps/renovatebot
        property: renovate_github_token_public
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: kv/apps/renovatebot
        property: renovate_token_rw