nfs:
  server: 10.20.0.21
  path: /mnt/tank/containers
  mountOptions:
    - nfsvers=3
  volumeName: nfs-subdir-external-provisioner-root
  # Reclaim policy for the main nfs volume
  reclaimPolicy: Retain
storageClass:
  #reclaimPolicy: Retain
  name: nfs-subdir
  provisionerName: testg
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
