---
defaultPodOptions:
  securityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 65539

controllers:
  jellyseerr:
    type: statefulset
    # type: statefulset
    # replicas: 3
    # statefulset:
    #   volumeClaimTemplates:
    #   - name: "storage"
    #     globalMounts:
    #       - path: /config
    #     accessMode: "ReadWriteOnce"
    #     size: "1Gi"
    #     storageClass: "nfs-csi"
    containers:
      app:
        image:
          repository: fallenbagel/jellyseerr
          tag: 2.5.2
          pullPolicy: IfNotPresent
service:
  app:
    controller: jellyseerr
    ports:
      http:
        port: 5055

ingress:
  app:
    className: "nginx-internal"
    hosts:
      - host: jellyseerr-k.bukla.hu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - jellyseerr-k.bukla.hu
        secretName: wildcard-bukla-tls
persistence:
  config:
    existingClaim: jellyseerr-conf
    globalMounts:
      - path: /config