secretRefs:
  existingSecret: n8n-secrets
  
queueMode:
  enabled: true
  workerReplicaCount: 1

taskRunners:
  enabled: true
  customConfig:
    enabled: true
    configMapName: "n8n-task-runner-extra"
    configMapKey: "n8n-task-runners.json"
  image:
    repository: harbor.raymol.com/library/custom-n8n-runner
    tag: "1.0.0"
database:
  type: postgresdb
  useExternal: true
  host: "psql.raymol.com"
  port: 5432
  database: n8n
  schema: "public"
  user: n8n
  passwordSecret:
    name: "n8n-secrets"
    key: "psql-password"

redis:
  enabled: true
  useExternal: true
  host: "redis.redis.svc.cluster.local"
  port: 6379
  username: ""
  passwordSecret:
    name: "n8n-secrets"
    key: "redis-password"
